### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by longnd** [minhtienvu/nimble_assignment#12]
Hello Tien 👋 , 
Thank you for your effort on the code submission. I am Long, engineering lead at Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, and thus I will create issues where I think there could be more improvements regarding your performance here.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to raise your questions or share your opinions about the implementation (if any) during the process.

If we are aligned on any issue, and you would like to correct them, please address the issue using a proper git flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready), and I will follow up on those fixes. Please note that you don't have to close any of my created issues after merging your PRs, I will help verify and close them for you once they pass. 😇

We expect the code review process to be completed within 2-3 days at most. As a result, ensure you are responsive during this process. If you need additional time, please inform us right away so that we can plan accordingly.

In the end, I really do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by minhtienvu** [comment]
@longnd
Hi Mr. Long,
I’m waiting for you all day to receive your feedback to check my technical and problem-solving skills. I hope that I will gain more knowledge from your feedback. Thanks for your support

**Comment by longnd** [comment]
I have completed the first round of reviews. Please provide your feedback on all open issues.

**Comment by longnd** [comment]
Thank you for the feedback on all open issues and the fixes done so far.

As explained above, we aim to keep the code review process short, so let's end this phase now. We have enough statistics for the assessment, but you can still make further improvements if you would like.

Our team will provide feedback to you by email.

**Comment by minhtienvu** [comment]
@longnd
Morning Mr. Long, 👋
I'm glad to hear your news. Thank you for your support and suggestion during the code review process. I have learned too much from your issues. 

I'm obsessed with perfection; therefore, I will continue to improve, refactor my code and resolve your issues. Because I believe that the more problems I resolve, the more knowledge I can gain 💪

Thank you so much, and have a good day 🍀
