### ISSUE TITLE
[Chore] Improve the code organization

### ISSUE THREAD

**Issue by longnd** [minhtienvu/nimble_assignment#16]
Issue
--
The `search_words_from_file()` function in GoogleSearcherServices service has too many responsibilities:
- Validate the uploaded CSV file and parse it
- Create a `file upload` record in the DB
- Loop through the keyword list and trigger Google Search API to get the search result for each keyword
- Store the keyword and its search result in DB
https://github.com/minhtienvu/nimble_assignment/blob/686cea2e549dd791340933e93404d9be9c0c77de/app/services/google_searcher_services.rb#L5-L31
It is too complicated, violates the Single responsibility principle, and is hard to maintain.

Expected
--
The source code is well-organized, and each function is responsible for a single responsibility only.

**Comment by minhtienvu** [comment]
@longnd 
I got your point, I will refactor it. Thanks

**Comment by minhtienvu** [comment]
@longnd 
I did refactor my code on google_seacher_service according to S(SOLID) pattern, please check it. Thanks

**Comment by longnd** [comment]
thank you for spending time on the fix :)
