### ISSUE TITLE
[Feature] Validate the uploaded file

### ISSUE THREAD

**Issue by longnd** [minhtienvu/nimble_assignment#17]
Issue
--
The application only validates the number of keywords in the file
https://github.com/minhtienvu/nimble_assignment/blob/686cea2e549dd791340933e93404d9be9c0c77de/app/services/google_searcher_services.rb#L35-L39

but does not validate the file itself, e.g. the file must be present and in CSV upload. The client-side validation isn't sufficient. 

Expected
---
The uploaded CSV file should be validated to ensure it is submitted in the correct format.

**Comment by minhtienvu** [comment]
@longnd 
I got your point, so I will add validations on the back-end site. Thanks

**Comment by minhtienvu** [comment]
@longnd 
I just added validation when the file type is not csv. Please check it. Thanks

**Comment by longnd** [comment]
Thank you for spending time on the fix.
